### PR TITLE
Fix takeoff complete check for ON_TAKEOFF_COMPLETE

### PR DESCRIPTION
**Pull request by MaEtUgR**
#### Add a link of the Jira Task
https://auterion.atlassian.net/browse/APX4-1950

#### Does this PR need to be backported to the stable release?
I don't know @mrivi ?

#### Does this PR need to update any documentation (readme, confluence, gitbook, etc.)?
NO!

#### Describe your solution
The MAVSDK `_telemetry->subscribe_in_air()` state represents if the vehicle reports it is actually in air. That is already the case while it is still taking off and not having reached the desired takeoff altitude yet and hence not completed the takeoff. This is a problem because it was assumed that as soon as the vehicle is in air the takeoff is done and then it continued the mission too early and hence sped up too fast already from the ground.

#### Test data / coverage
This is untested because I did not set up the environment with all the dependencies to verify just this condition.
@TSC21 could you please give it a quick run in simulation with custom action #0 to verify it works? A ulog would also be useful such that we can verify it actually doesn't continue and go fast too early.

### CODE REVIEW

**Comment by TSC21** [comment]
Can you format the code with the style fixer?

**Comment by MaEtUgR** [comment]
Sure! I didn't know it exists. It was super easy to use thanks for that 👍

**Comment by TSC21** [comment]
@MaEtUgR this seems to be working properly. Though as you can see from the log [here](https://drive.google.com/file/d/1OjUfEk-8sInZeG604jgWPQ5ejEgUlw0Q/view?usp=sharing), for some reason the land detector on the `iris` model doesn't seem to work very well for some reason.

Other than that, I fixed another important thing (last commit).

**Comment by MaEtUgR** [comment]
Thank you @TSC21 ! I had a look at the log and it solves the original jira issue. The takeoff after the delivery is completed with the expected type and speed before proceeding:
image

**Pull request merged**
