### PR TITLE
Adapt to modified, now pure-cmake langing-mapper package

### PR DESCRIPTION
**Pull request by bastianhjaeger**
#### Add a link of the Jira Task
Jira Task: *none*

#### Does this PR need to update any documentation (readme, confluence, gitbook, etc.)?
NO!

#### Describe your solution
Related to https://github.com/Auterion/landing_mapper/pull/10 and necessary to build with the updated dependency.

#### Test data / coverage
How was this tested? What Platforms were covered?
* Laptop

### CODE REVIEW

**Comment by TSC21** [comment]
There are a lot of changes in this PR that are unrelated to the PR itself. Lot of commented code that should not be commented as well.

**Comment by DanMesh** [comment]
Yes, that's what I mean. In ce957dc70427ca183eda057e4f507b3994df2487 I've distilled it down to what I believe are the "related changes", and those work as expected.
The question is, are there other changes we are waiting for that I'm not aware of? Particularly those that might affect my upcoming work on safe landing.

**Comment by TSC21** [comment]
> Yes, that's what I mean. In [ce957dc](https://github.com/Auterion/autopilot_manager/commit/ce957dc70427ca183eda057e4f507b3994df2487) I've distilled it down to what I believe are the "related changes", and those work as expected. The question is, are there other changes we are waiting for that I'm not aware of? Particularly those that might affect my upcoming work on safe landing.

@DanMesh ok can you open a PR with only that change and then we can bring it in? It will supersed this one.

**Comment by TSC21** [comment]
Superseded by #28.

**Pull request closed without merging**
